### ISSUE TITLE
要不要翻译个中文的设置界面

### ISSUE THREAD

**Issue by xiashali** [cloud-emoticon/SmallCloudEmoji#1]
文本怎么弄的，我试试手。

**Comment by sorz** [comment]
这大概是一个 bug，我有写中文翻译。
请问你系统当前的语言是？

**Comment by sorz** [comment]
翻译可参照这些文件的格式：
英文 https://github.com/BlueN/SmallCloudEmoji/tree/master/app/src/main/res/values
中文 https://github.com/BlueN/SmallCloudEmoji/tree/master/app/src/main/res/values-zh

求日文翻译（
