### ISSUE TITLE
关于应用的命名

### ISSUE THREAD

**Issue by xiashali** [cloud-emoticon/SmallCloudEmoji#2]
Emoticon/kaomoji/顔文字 主要指的是 :) (^_^) (>'_')> 那样用字符构造的表情符号。 
英语称 :) (^_^) (>'_')> 这些东西为「emoticon」，日语称其「kaomoji（顔文字）」。其中最典型的是 :) 这样笑脸类的表情符号，这一类在英语里通常称作「smiley」，它们在即时通讯工具等环境中时常也是图形，如 Unicode Emoticons block 里展示的那样。
而 emoji/絵文字 的题材远远超出了表情，并且一定是图形，不是用各式字符拼凑的。

综上所述，应为kaomoji而不是emoji

以上内容来自知乎

**Comment by sorz** [comment]
是的.. 因为是英语，所以目前用了 _Small Cloud *_Emoticon**\* 这个名称。
README、Google Play、软件英文界面都用了这个名称，代码是在 cfcc74f669fd3fed297f1239fe80e4a1b9e3f0fe 中统一改为 _emoticon_ 的..
包名和 repository 因为很难做到无痛更改，也与用户无关，所以就保留 _emoji_ 了…
